on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

name: "Pull Request"

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    uses: ./.github/workflows/part_tool_versioning.yml

  test:
    name: "Test"

    needs: ["detectToolVersions"]

    uses: ./.github/workflows/part_test.yml
    with:
      otpVersion: "${{ needs.detectToolVersions.outputs.otpVersion }}"
      rebarVersion: "${{ needs.detectToolVersions.outputs.rebarVersion }}"

  docs:
    name: "Docs"

    needs: ["detectToolVersions"]

    uses: ./.github/workflows/part_docs.yml
    with:
      otpVersion: "${{ needs.detectToolVersions.outputs.otpVersion }}"
      rebarVersion: "${{ needs.detectToolVersions.outputs.rebarVersion }}"
